import Vue from 'vue'
import Vuex from 'vuex'

import actions from './action'
import getters from './getter'
import mutations from './mutation'

Vue.use(Vuex)

export default new Vuex.Store({
	state: {
		// 当前登录用户信息
		userInfo: null,
		// 弹窗状态
		popups: {
			// 是否登录
			isLogining: false,
			// 是否注册
			isRegistering: false
		},
		// 背景图是否清晰
		isBgClear: true,
		// 是否正在底部
		isBottom: false,
		// 搜索框选中
		searchSelect: 'movie',
		// 搜索框关键字
		keyword: '',
		// 当前中文名（电影、影人）
		nameZh: '',
		// subject页面子组件加载状态
		subject: {
			// 获取数据是否结束
			isDetailsDone: false,
			isZhihuDone: false,
			isResourceDone: false,
			isSceneDone: false,
			isNmDone: false,
			// 获取数据是否成功
			isResourceGot: false,
			isSceneGot: false,
		},
		// 特定页面背景图片列表
		specialBgList: [],
		// 默认页面背景图片列表
		defaultBgList: [
			'https://img1.doubanio.com/view/photo/l/public/p2205392045.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2201817941.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2107662390.webp',
			'https://img1.doubanio.com/view/photo/l/public/p457875621.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2574726096.webp',
			'https://img1.doubanio.com/view/photo/l/public/p760049048.webp',
			'https://img1.doubanio.com/view/photo/l/public/p593669789.webp',
			'https://img1.doubanio.com/view/photo/l/public/p669614919.webp',
			'https://img1.doubanio.com/view/photo/l/public/p1144319199.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2413264020.webp',
			'https://img1.doubanio.com/view/photo/l/public/p854142891.webp',
			'https://img1.doubanio.com/view/photo/l/public/p828797577.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2413244447.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2399456352.webp',
			'https://img1.doubanio.com/view/photo/l/public/p570509636.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2581352902.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2160111760.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2175767572.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2561638425.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2002648846.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2277484017.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2277484043.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2413274720.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2512344271.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2505708957.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2505722998.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2209554441.webp',
			'https://img1.doubanio.com/view/photo/l/public/p1785901007.webp',
			'https://img1.doubanio.com/view/photo/l/public/p1784571177.webp',
			'https://img1.doubanio.com/view/photo/l/public/p1790687383.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2199558687.webp',
			'https://img1.doubanio.com/view/photo/l/public/p678292805.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2533777730.webp',
			'https://img1.doubanio.com/view/photo/l/public/p457210632.webp',
			'https://img1.doubanio.com/view/photo/l/public/p458693958.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2573230297.webp',
			'https://img1.doubanio.com/view/photo/l/public/p595286122.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2533577392.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2553461442.webp',
			'https://img1.doubanio.com/view/photo/l/public/p457404340.webp',
			'https://img1.doubanio.com/view/photo/l/public/p1129219206.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2572441306.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2414022155.webp',
			'https://img1.doubanio.com/view/photo/l/public/p1026382162.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2107947301.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2107964037.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2019255582.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2505927197.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2474261199.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2176239495.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2181560359.webp',
			'https://img1.doubanio.com/view/photo/l/public/p2506337058.webp',
		],
		// 电影台词列表
		movieLinesShort: [
			'May the Force be with you',
			'Stupid is as stupid does',
			'对不起，我是警察',
			'All is well',
			'You got your towl?',
			'大哥大嫂过年好',
			'安红，饿想你!',
			'大哥，你是了解我的',
			'他好像条狗啊',
			'我养你啊',
			'常威，你还说你不会武功!',
			'你怎么了小强？',
			'我读书少，你不要骗我',
			'不要误会，我不是针对你',
			'你这瓜保熟吗？',
			'吔屎啦，梁非凡',
			'我要打十个！',
			'你知道什么是铛铛铛铛吗?',
			'这种要求我从来没有见过',
			'不上班行不行啊？',
			'我很孤独，英文怎么讲？',
			'我全都要',
			'风华绝代的石榴姐',
			'算了吧，都烧焦了',
			'喔你个头啊！',
			'叶师傅！切他中路!',
		],
		currentMovieLinesLong: Math.round(Math.random() * 70),
		movieLinesLong: [

			'May the Force be with you',
			'Stupid is as stupid does',
			'对不起，我是警察',
			'All is well',
			'You got your towl?',
			'大哥大嫂过年好',
			'安红，饿想你!',
			'大哥，你是了解我的',
			'他好像条狗啊',
			'我养你啊',
			'常威，你还说你不会武功!',
			'你怎么了小强？',
			'我读书少，你不要骗我',
			'不要误会，我不是针对你',
			'你这瓜保熟吗？',
			'吔屎啦，梁非凡',
			'我要打十个！',
			'你知道什么是铛铛铛铛吗?',
			'这种要求我从来没有见过',
			'不上班行不行啊？',
			'我很孤独，英文怎么讲？',
			'我全都要',
			'风华绝代的石榴姐',
			'算了吧，都烧焦了',
			'喔你个头啊！',
			'叶师傅！切他中路!',

			'每个人都有一个习惯，我的习惯是在这里等阿may下班',
			'人和妖精都是妈生的，人是人他妈生的，妖是妖它妈生的',
			'你抓周树人和我鲁迅有什么关系',
			'就算是一条内裤，一张卫生纸，都有它本身的用处',
			'长夜漫漫，无心睡眠，我以为只有我睡不着觉，没想到晶晶姑娘你也一样',
			'人类可以搭乘太空船到月球，但却没办法看穿每个人心里的宇宙',
			'我就是美貌与智慧并重，英雄与侠义的化身———唐伯虎！',
			'我对你的敬仰有如滔滔江水，连绵不绝，又如黄河泛滥，一发不可收拾',
			"如果你一定要叫我跑龙套的，可不可以不要加一个'死'字在前面",
			'昨晚你睡觉的时候喊白晶晶98次，喊紫霞784次，这个人一定上辈子欠了你很多钱',
			'表面上看这是一个吹风机，实际上它是一个刮胡刀',
			'做人如果没有梦想，那和咸鱼有什么区别',
			"Life was like a box of chocolates, you never know what you're going to get",
			'Do not go gentle into that good night',
			'别人笑我太疯癫，我笑他人看不穿',
			'我左青龙，右白虎，老牛在腰间，龙头在胸口，人挡杀人，佛挡杀佛！',
			'腰里揣着死耗子还冒充打猎的',
			'人是人他妈生的，妖是妖他妈生的，只要你有一颗善良的心就不再是妖，是人妖',
			'实不相瞒，我看阁下从头到脚指头，没有一处不入乞丐的型格啊！',
			'象你这样出色的男人，无论在什么地方，都像漆黑中的萤火虫一样，那样的鲜明，那样的出众',
			'你那忧郁的眼神，稀嘘的胡喳子，神乎其神的刀法，和那杯Dry Martine，都深深地迷住了我',
			'只要你说我行，就算全天下的人都说我不行，我也不在乎',
			'曾经有一份真诚的爱情放在我面前，我没有珍惜，等到失去的时候我才后悔莫及，人世间最痛苦的事莫过于此',
			'一支穿云箭，千军万马来相见',
			'除暴安良是我做市民的责任，积德行善是我的兴趣',
			'难道我学过如来神掌也要说给你听吗？',
			'你们丐帮几千万人，一天不解散，我怎么心安？',
			'八目共赏，赏花赏月赏秋香！',
			'大家都听到了，是他叫我打我才打的',
			'不要因为我是娇花而怜惜我',
			'你好大的官威呀，包大人',
			'我酱爆，在这moment，要爆了~',
			'别以为你长得帅我就不打你',
			'紫霞在你心目中是不是一个惊叹号？还是一个句号？你脑袋里是不是充满了问号？',
			'我一进门就看见常威在打来福',
			'民族英雄——小平 赠',
			'不管怎么说，他始终是我心目中独一无二、风度翩翩的猪肉王子',
			'你肚子饿不饿，我煮碗面给你吃',
			'到底是让我打他还是打他妈啊！你搞得我好乱啊！',
			'我们就是东淫西贱，南荡北色',
			'我靠，躺着也能中枪',
			'人家两个男才女貌，哪轮得到你这个妖怪来反对',
			'以前陪我看月亮的时候，叫我小甜甜，现在新人胜旧人啦！叫人家牛夫人',
			'那么在哪里才能买到呢',
			'越来越接近秋香姐，今天的心情是大不同啊，大不同',
			'扶老太太过马路我每个星期都做一次，如果是碰到国定假日的话，我还做两三次呢',
			'落花有意随流水，而流水无心恋落花',
			'我的意中人是个盖世英雄，有一天他会踩着七色的云彩来娶我',
			'我好孤独，英文怎么讲？',
			'我还是希望你叫我的全名，达文西',
		],
	},
	getters,
	mutations,
	actions
})